added Auto-Anvil
Slimefun/Wiki pull request #107
Opened 2021-01-19 11:28 UTC by MeerBiene

Please tell me if the page doesnt meet your requirements, I edited this in the github web IDE so yeah :D

2021-01-20 18:59 UTC, Phoenix-Starlight requested changes
Some changes and fixes suggested.

2021-01-20 18:59 UTC, Phoenix-Starlight commented on pages/Auto-Anvil
> +Place the item you want to repair together with "Duct Tape" in the machine and wait. (You need energy for it to work)
The other method of usage would be to combine enchantment books with items. Also link duct tape item if it does exist.

2021-01-20 18:59 UTC, Phoenix-Starlight commented on pages/Auto-Anvil
> +# Auto-Anvil
You do not need a header for the block/item name.

2021-01-20 18:59 UTC, Phoenix-Starlight commented on pages/Auto-Anvil
> +There are 2 tiers of this machine. Tier 1 has a Repair Factor of 10%, Tier2 20%.
Minor typo, 'Tier2' should be 'Tier 2'

2021-01-20 18:59 UTC, Phoenix-Starlight commented on pages/Auto-Anvil
> +The auto anvil is one of the more complicated crafting recipes. You can find it under the category "Energy & Electricity" on the second page.
Maybe link to the Electric Machines category in the wiki.

2021-01-20 19:23 UTC, MeerBiene commented
Okay,time to edit this in a real editor. Should I also put a section about crafting or is that self explanatory?

2021-01-21 03:38 UTC, Phoenix-Starlight commented
> Okay,time to edit this in a real editor. Should I also put a section about crafting or is that self explanatory?

They can find it in the in-game guide at /sf guide. So no.

2021-01-24 16:01 UTC, TheBusyBiscuit commented
The file is also missing an ending (`.md`)

2021-01-25 01:01 UTC, svr333 commented
Just wanted to mention #93 also adds this page (and that it still hasnt gotten a second person to review it)

2021-01-31 12:23 UTC, TheBusyBiscuit commented
Closed

2021-01-31 12:23 UTC, closed without merging