Add Magical Armor Page
Slimefun/Wiki pull request #138
Opened 2021-06-06 13:17 UTC by svr333

- Adds the Magical Armor page
- Fixes an old link to Slime Armor

2021-06-07 19:10 UTC, Phoenix-Starlight approved these changes
LGTM

2021-07-12 18:59 UTC, TheBusyBiscuit requested changes

2021-07-12 18:59 UTC, TheBusyBiscuit commented on pages/Magical-Armor.md
> +When wearing the Bee Boots, you gain Jump Boost III and you negate fall damage.
I think it would be better to call them "Ender Armor", "Slime Armor", "Glowstone Armor", ....
respectively.

2021-07-19 17:01 UTC, Phoenix-Starlight approved these changes
Looks good.

2021-08-10 23:42 UTC, Sfiguz7 approved these changes

2021-08-10 23:43 UTC, merged