Add medical supplies page
Slimefun/Wiki pull request #160
Opened 2021-09-09 15:06 UTC by svr333

Adds the Medical-Supplies page and fixes 1 wrong link

2021-09-10 03:02 UTC, Phoenix-Starlight approved these changes

2021-09-10 03:05 UTC, Phoenix-Starlight approved these changes
LGTM

2021-09-23 16:29 UTC, Sfiguz7 requested changes
Since all of the ones below had a double "will" form I think the top two should as well. Other than that LGTM

2021-09-23 16:29 UTC, Sfiguz7 commented on pages/Medical-Supplies.md
> +Using this item will restore 2 hearts and extinguishes fire if you were to be on fire.
```suggestion
Using this item will restore 2 hearts and will extinguish fire if you were to be on fire.
```

2021-09-23 16:29 UTC, Sfiguz7 commented on pages/Medical-Supplies.md
> +Using this item will restore 4 hearts and extinguishes fire if you were to be on fire.
```suggestion
Using this item will restore 4 hearts and will extinguish fire if you were to be on fire.
```

2021-09-23 18:17 UTC, Sfiguz7 approved these changes
LGTM

2021-09-30 00:51 UTC, Phoenix-Starlight approved these changes
LGTM

2021-09-30 09:49 UTC, merged