Add Technical Gadgets pages
Slimefun/Wiki pull request #161
Opened 2021-09-09 15:55 UTC by svr333

## Changes
- Adds Technical Gadgets page
- Adds Jetpacks page
- Adds Multi Tools page
- Adds Jetboots page
- Fixes multimeter links
- Adds Android-Memory-Core to Technical Components page

2021-09-30 00:52 UTC, Phoenix-Starlight approved these changes

2021-09-30 10:32 UTC, WalshyDev requested changes

2021-09-30 10:32 UTC, WalshyDev commented on pages/Multi-Tools.md
> +To use, right click, to switch modes, crouch and right click.
```suggestion
Right-click to use. Crouch + right-click to switch modes\
```

2021-09-30 10:32 UTC, WalshyDev commented on pages/Multi-Tools.md
> +Each time you use it, it will use up some energy.
what's "some energy" how much? does it depend on the tier?

2021-09-30 10:32 UTC, WalshyDev commented on pages/Technical-Gadgets.md
> +The Solar Helmet, when worn, will charge any items and armor in that user's inventory.
```suggestion
The Solar Helmet when worn will charge any electric armor and anything electric in the player's hands.
```

2021-09-30 11:35 UTC, WalshyDev approved these changes
lgtm

2021-10-01 19:19 UTC, WalshyDev requested changes

2021-10-01 19:19 UTC, WalshyDev commented on pages/Technical-Gadgets.md
> +When worn, this piece of head armour gives you night vision.
We should really standardize a language here. Do we want British English or American English?

2021-10-01 19:19 UTC, WalshyDev commented on pages/Technical-Gadgets.md
> +The Solar Helmet when worn will charge any electric armor and anything electric in the player's hands.
You use American English here :NotLikeThis:

2021-10-01 19:22 UTC, WalshyDev submitted a review, later dismissed
LGTM

2021-10-01 19:22 UTC, Sefiraat commented on pages/Technical-Gadgets.md
> +The Parachute can be used to slowly descent when you're in the air. You need to wear it and crouch for it to activate.
```suggestion
The Parachute can be used to slowly decend while you're in the air. You need to wear it and crouch for it to activate.
```

2021-10-01 19:24 UTC, Sfiguz7 approved these changes
LGTM

2021-10-01 19:24 UTC, Sfiguz7 commented on pages/Jet-Boots.md
> +|  Tier   | Storage Capacity | Speed | Acurracy |
```suggestion
|  Tier   | Storage Capacity | Speed | Accuracy |
```

2021-10-01 19:24 UTC, Sfiguz7 commented on pages/Jet-Boots.md
> +|  Tier   | Storage Capacity | Speed | Acurracy |
We were in a call and he already changed the requested change

2021-10-01 19:32 UTC, Sefiraat approved these changes
lgtm

2021-10-01 19:33 UTC, merged