Create Climbing Pick page
Slimefun/Wiki pull request #167
Opened 2021-10-01 21:49 UTC by svr333

## Changes
- Create Climbing Pick page
- Add Climbing Pick to Tools category

2021-10-02 09:41 UTC, WalshyDev requested changes

2021-10-02 09:41 UTC, WalshyDev commented on pages/Climbing-Pick.md
> +## Climbing Pick Settings
```suggestion

## Climbing Pick Settings
```

2021-10-02 09:41 UTC, WalshyDev commented on pages/Climbing-Pick.md
> +It can be enchanted with efficiency to speed up the climbing process!
```suggestion
It can be enchanted with the **efficiency** enchantment to speed up the climbing process! 
```

2021-10-02 09:41 UTC, WalshyDev commented on pages/Climbing-Pick.md
> +By default, you need to have two of these in order for it to work, one if your off-hand and one in your main hand.
one if your off-hand LUL
```suggestion
By default, you need to have two of these in order for it to work, one in both your main-hand and your off-hand.  
```

2021-10-06 04:10 UTC, Phoenix-Starlight submitted a review, later dismissed
LGTM

2022-01-18 16:36 UTC, WalshyDev requested changes

2022-01-18 16:38 UTC, svr333 commented on pages/Climbing-Pick.md
> +| dual-wielding | If enabled, you will have to use two Climbing Picks at once in order to climb. | boolean | true        |
```suggestion
| dual-wielding | If enabled, you will have to use two Climbing Picks at once in order to climb. | boolean | true          |
```

2022-01-18 16:39 UTC, WalshyDev approved these changes
LGTM

2022-01-19 01:56 UTC, Phoenix-Starlight approved these changes

2022-01-19 01:56 UTC, merged