Solar Panel -> Photovoltaic Cell
Slimefun/Wiki pull request #180
Opened 2021-12-21 13:14 UTC by svr333

2021-12-26 19:19 UTC, Phoenix-Starlight approved these changes

2021-12-28 15:18 UTC, TheBusyBiscuit requested changes

2021-12-28 15:18 UTC, TheBusyBiscuit commented on pages/Ferrosilicon.md
> +* [Solar Panel](https://github.com/Slimefun/Slimefun4/wiki/Photovoltaic-Cell)
```suggestion
* [Photovoltaic Cell](https://github.com/Slimefun/Slimefun4/wiki/Photovoltaic-Cell)
```

2021-12-28 15:33 UTC, svr333 commented on pages/Ferrosilicon.md
> +* [Solar Panel](https://github.com/Slimefun/Slimefun4/wiki/Photovoltaic-Cell)
ah yes

2021-12-31 17:41 UTC, TheBusyBiscuit approved these changes

2022-01-01 01:22 UTC, Phoenix-Starlight approved these changes

2022-01-01 01:23 UTC, merged