Add VillagerUtil to the addons page
Slimefun/Wiki pull request #188
Opened 2022-01-30 18:01 UTC by Apeiros-46B

Adds VillagerUtil to the addons page

2022-01-30 18:07 UTC, Sefiraat commented on pages/Addons.md
> +VillagerUtil | Apeiros-46B | <details><summary>expand</summary>VillagerUtil adds a few tools that allow for easily transporting villagers, curing zombified villagers, cycling trades, and more.</detai
```suggestion
VillagerUtil | Apeiros-46B | <details><summary>expand</summary>VillagerUtil adds a few tools that allow for easy transportation of villagers, curing zombified villagers, cycling trades and more.</details> | [Readme](https://github.com/Apeiros-46B/VillagerUtil/blob/main/README.md) | [GitHub](https://github.com/Apeiros-46B/VillagerUtil) | [Builds](https://thebusybiscuit.github.io/builds/Apeiros-46B/VillagerUtil/main)
```

2022-01-30 19:02 UTC, TheBusyBiscuit requested changes
What @Sefiraat said

2022-01-31 00:38 UTC, TheBusyBiscuit approved these changes

2022-01-31 23:13 UTC, svr333 approved these changes

2022-01-31 23:13 UTC, merged