Added Missile Warfare To Community Addons
Slimefun/Wiki pull request #192
Opened 2022-02-10 10:37 UTC by koiboi-dev

I've created a plugin for slimefun and added it to the community projects of the addons list.

2022-02-10 11:12 UTC, Sefiraat commented on pages/Addons.md
> +MissileWarfare | Kaiyan2006 | <details><summary>expand</summary>Missile Warfare adds a bunch of missiles to slime fun that can be fired at others!</details> | [GitHub](https://github.com/koiboi-dev/M
```suggestion
MissileWarfare | Kaiyan2006 | <details><summary>expand</summary>Missile Warfare adds a bunch of missiles to Slimefun that can be fired at others!</details> | [GitHub](https://github.com/koiboi-dev/MissileWarfare) | N/A | [Releases] (https://github.com/koiboi-dev/MissileWarfare/releases)
```

2022-02-10 11:12 UTC, Sefiraat commented on pages/Addons.md
> +MissileWarfare | Kaiyan2006 | <details><summary>expand</summary>Missile Warfare adds a bunch of missiles to slime fun that can be fired at others!</details> | [GitHub](https://github.com/koiboi-dev/M
Is the addon called MissileWarfare or Missile Warfare - you call it both in here - one or the other I think :)

2022-02-10 14:21 UTC, svr333 commented on pages/Addons.md
> +MissileWarfare | Kaiyan2006 | <details><summary>expand</summary>Missile Warfare adds a bunch of missiles to slime fun that can be fired at others!</details> | [GitHub](https://github.com/koiboi-dev/M
how did I let that past :notlikethis:

2022-02-12 02:01 UTC, Phoenix-Starlight commented
Huh, some random conflict... must be because I merged! Well, I leave it to you to either sync it up or fix it. @koiboi-dev

2022-02-20 06:47 UTC, Phoenix-Starlight commented
Ok I resolved the conflicts for you. Please look over the files again and change and make any corrections as needed. (And reviews to be resolved). I will look at this again once you're happy with it.

2022-03-03 06:16 UTC, koiboi-dev commented
Ok I think I'm happy with how the wiki implementation looks

2022-03-03 09:51 UTC, TheBusyBiscuit requested changes

2022-03-04 14:12 UTC, koiboi-dev reviewed
Oh I didn't see that, sorry for not noticing stuff like this

2022-03-04 14:14 UTC, koiboi-dev commented
It should be all good now, sorry for making this such a hassle

2022-03-04 14:27 UTC, Sefiraat approved these changes
LGTM 👍

2022-03-05 02:22 UTC, Phoenix-Starlight approved these changes
Congrats on making it through!

2022-03-05 12:44 UTC, svr333 approved these changes

2022-03-05 12:44 UTC, merged