Change units of time
Slimefun/Wiki pull request #195
Opened 2022-02-24 04:21 UTC by Phoenix-Starlight

One of the PRs (hopefully just one!) to replace units of time to something more flexible and accurate.

2022-02-24 11:04 UTC, svr333 submitted a review, later dismissed
Slimefun so the abbreviation would be Sf :)

2022-02-24 11:04 UTC, svr333 commented on pages/Animal-Growth-Accelerator.md
> +**Power Usage**: 28 J/SF TickF tick
```suggestion
**Power Usage**: 28 J/SF Tick
```

2022-02-25 02:16 UTC, Phoenix-Starlight commented on pages/Animal-Growth-Accelerator.md
> +**Power Usage**: 28 J/SF TickF tick
Hm- sed didn't catch that? Oh noes!

2022-02-25 13:13 UTC, svr333 requested changes
all the tables are gonna need to be reformatted too

2022-03-01 13:08 UTC, svr333 requested changes

2022-03-01 13:08 UTC, svr333 commented on pages/Freezer.md
> +| :--: | :----:       | :--------------: | :----: |
```suggestion
| Tier |     Power    | Speed Multiplier | Buffer |
| :--: | :----------: | :--------------: | :----: |
```

2022-03-01 13:08 UTC, svr333 commented on pages/GPS-Transmitter.md
> +| ----                      | ------ | -----------  | ------------- | ---------- |
```suggestion
| Tier                      | Buffer | Consumption  | Tier Modifier | Tier Bonus |
| ------------------------- | ------ | ------------ | ------------- | ---------- |
```

2022-03-01 13:08 UTC, svr333 commented on pages/Heated-Pressure-Chamber.md
> +| :--: |    :----:    | :--------------: |
```suggestion
| Tier |    Power     | Speed Multiplier |
| :--: | :----------: | :--------------: |
```

2022-03-01 13:08 UTC, svr333 commented on pages/Solar-Generator.md
> +| :------------------------ |       :------------------------------:       |
```suggestion
| Tier                      | Energy                                       |
| :------------------------ | :------------------------------------------: |
```

2022-03-01 13:08 UTC, svr333 commented on pages/Reactors.md
> +| :------------------  |    :-----:    | :----: | ----------------------------------- | ------------------------ | ---------------------------- |
```suggestion
| Type                 | Power         | Buffer | Fuel                                | Cooling                  | Side Effects                 |
| :------------------  | :------------: | :----: | ----------------------------------- | ------------------------ | ---------------------------- |
```

2022-03-01 13:08 UTC, svr333 commented on pages/Lava-Generator.md
> +| :--: |    :----:    | :----: |
```suggestion
| Tier |    Energy    | Buffer |
| :--: | :----------: | :----: |
```

2022-03-01 15:50 UTC, Phoenix-Starlight commented
Ah I see now!

2022-05-08 19:32 UTC, Phoenix-Starlight commented
Fixes #198 (just so this automatically closes)

2022-05-08 23:36 UTC, Phoenix-Starlight commented
But.. it's not changed here? If you mean the other one, I reverted that.

2022-05-10 09:48 UTC, svr333 commented
yeah but you mentioned that this PR fixes #198 which is unrelated

2022-05-11 04:57 UTC, Phoenix-Starlight commented
Oh. yeah.

2022-05-28 11:26 UTC, WalshyDev approved these changes

2022-05-28 20:48 UTC, merged