Add Bump to the Addon page
Slimefun/Wiki pull request #204
Opened 2022-04-20 15:29 UTC by haiman233

2022-04-20 16:14 UTC, Sefiraat commented on pages/Addons.md
> +Bump | SlimefunGuguProject | <details><summary>expand</summary>A Slimefun4 addon that adds magic weapon, food and appraisal system.Through the appraisal system, you could even get the 8 stars weapon
```suggestion
Bump | SlimefunGuguProject | <details><summary>expand</summary>A Slimefun4 addon that adds magic weapons, food and an appraisal system. Through the appraisal system, you could even get an 8 star weapon or armor.</details> | [Readme](https://github.com/SlimefunGuguProject/Bump/blob/main/README.md) | [Github](https://github.com/SlimefunGuguProject/Bump) | [Builds](https://builds.guizhanss.net/SlimefunGuguProject/Bump/main/)
```

2022-04-20 16:16 UTC, haiman233 commented
thx for a lot

2022-04-23 03:43 UTC, Phoenix-Starlight approved these changes

2022-04-23 03:44 UTC, Phoenix-Starlight approved these changes
Conflict resolved.

2022-04-23 11:20 UTC, svr333 commented
is it intended that the builds page is not in english?

2022-04-23 11:25 UTC, TheBusyBiscuit requested changes
"Builds" links to a third-party website here. This could be misleading as people may think it would link to OUR builds page.

I am not sure if we want to link to sites other than GitHub, CurseForge, Spigot or our own builds page in the first place. So I am rejecting this for now.
If you were to publish your addon on Spigot, CF or GitHub, feel free to make a new PR.

2022-04-23 11:25 UTC, closed without merging

2022-04-23 20:50 UTC, ybw0014 commented
Hi, I wonder if you would accept changing the `Builds` to `External Builds` or `Builds (External)`.
The external builds page is modified from your builds page and is fully open source (https://github.com/ybw0014/maven-builds). Currently, it has no other language than Simplified Chinese. I may add the i18n module to it asap.

2022-04-24 05:33 UTC, Phoenix-Starlight commented
I would accept that change, as it would notify users that it links to a third-party.