Change 'ticks' to 'SF ticks'
Slimefun/Wiki pull request #210
Opened 2022-05-29 18:43 UTC by Phoenix-Starlight

2022-05-29 20:05 UTC, svr333 commented
why is every one of your prs 545435 commits?

2022-05-30 18:39 UTC, Phoenix-Starlight commented
Uhhhh due to the squashing it will always be that whenever I pull from upstream it will be my commits + 1. So. The only option would be to destroy the fork and refork.

2022-05-30 18:40 UTC, WalshyDev commented
Or just... pull the changes.

2022-05-30 18:40 UTC, Phoenix-Starlight commented
Actually, let me see if rollbacking to a place without my commits keeps it intact or not..

2022-05-30 18:49 UTC, Phoenix-Starlight commented
Pulling doesn't work because it says its up to date.

2022-05-30 18:50 UTC, WalshyDev commented
Then you aren't pulling from the right branch/origin

2022-05-30 19:23 UTC, Phoenix-Starlight commented
Ok, sorted out commit mess and all.

2022-05-30 21:25 UTC, svr333 submitted a review, later dismissed

2022-05-30 21:46 UTC, WalshyDev requested changes

2022-05-30 21:46 UTC, WalshyDev commented on pages/Server-Optimizations.md
> +The default setting for this task is set to 10 SF ticks (20 SF ticks = 1 second).<br>
This is correct as MC ticks

2022-06-01 03:50 UTC, Phoenix-Starlight commented on pages/Server-Optimizations.md
> +The default setting for this task is set to 10 SF ticks (20 SF ticks = 1 second).<br>
Oh, oops!

2022-06-02 12:43 UTC, svr333 approved these changes

2022-06-04 15:49 UTC, WalshyDev approved these changes

2022-06-04 15:49 UTC, merged