Add Spirits Unchained to the Addon Page
Slimefun/Wiki pull request #235
Opened 2022-11-04 22:06 UTC by JustAHuman-xD

With the addition of Spirits to the Builder, here is the PR for the wiki page

2022-11-05 08:20 UTC, Sefiraat commented on pages/Addons.md
> +SpiritsUnchained | JustAHuman_xD | <details><summary>expand</summary>Spirits Unchained is an addon focused on a new mechanic, Spirits! Spirits can be found roaming the wild or have a chance at gettin
```suggestion
SpiritsUnchained | JustAHuman_xD | <details><summary>expand</summary>Spirits Unchained is an addon focused on a new mechanic, Spirits! Spirits can be found roaming the wild or have a chance at getting released when killing a mob! Players can catch or bottle spirits and discover each types unique effects on its user. But be careful, spirits will not always be friendly. Spirits also has a built in guide book that you can access through the Slimefun guide if you need help using the addon!</details> | [Readme](https://github.com/JustAHuman-xD/SpiritsUnchained/blob/master/README.md) | [Github](https://github.com/JustAHuman-xD/SpiritsUnchained) | [Builds](https://thebusybiscuit.github.io/builds/JustAHuman-xD/SpiritsUnchained/master/)
```

2022-11-05 12:47 UTC, svr333 approved these changes

2022-11-05 13:03 UTC, Sefiraat approved these changes

2022-11-05 18:44 UTC, Phoenix-Starlight requested changes

2022-11-05 18:44 UTC, Phoenix-Starlight commented on pages/Addons.md
> +SpiritsUnchained | JustAHuman_xD | <details><summary>expand</summary>Spirits Unchained is an addon focused on a new mechanic, Spirits! Spirits can be found roaming the wild or have a chance at gettin
Possessive missing? Perhaps types' (type's?) or spirit's

2022-11-05 18:58 UTC, JustAHuman-xD commented on pages/Addons.md
> +SpiritsUnchained | JustAHuman_xD | <details><summary>expand</summary>Spirits Unchained is an addon focused on a new mechanic, Spirits! Spirits can be found roaming the wild or have a chance at gettin
Will do uno momento

2022-11-05 20:23 UTC, svr333 submitted a review, later dismissed

2022-11-06 14:07 UTC, svr333 approved these changes

2022-11-06 17:01 UTC, Phoenix-Starlight approved these changes
*Stamps it*

2022-11-06 17:10 UTC, svr333 approved these changes

2022-11-06 17:10 UTC, merged