Add Small Space Addon
Slimefun/Wiki pull request #243
Opened 2023-05-04 17:20 UTC by CAPS123987

2023-05-05 21:27 UTC, svr333 submitted a review, later dismissed

2023-05-08 00:29 UTC, Phoenix-Starlight requested changes

2023-05-08 00:29 UTC, Phoenix-Starlight commented on pages/Addons.md
> +SmallSpace | CAPS123987 | <details><summary>expand</summary>This Addon helps you when you have small space, just place a block right click it and you will be teleported on your space, you can also ad
```suggestion
SmallSpace | CAPS123987 | <details><summary>expand</summary>This addon helps you when you have small space, just place a block, right click it and you will be teleported to your space, you can also add members using /smallspace addMember</details> | [Readme](https://github.com/CAPS123987/SmallSpace/blob/master/README.md) | [Github](https://github.com/CAPS123987/SmallSpace) | [Builds](https://thebusybiscuit.github.io/builds/CAPS123987/SmallSpace/master/)
```
Minor nitpicks

2023-05-08 13:26 UTC, CAPS123987 commented on pages/Addons.md
> +SmallSpace | CAPS123987 | <details><summary>expand</summary>This Addon helps you when you have small space, just place a block right click it and you will be teleported on your space, you can also ad
Thank you 😉

2023-05-08 15:53 UTC, svr333 approved these changes

2023-05-08 15:54 UTC, svr333 approved these changes

2023-05-10 01:42 UTC, Phoenix-Starlight approved these changes

2023-05-10 01:43 UTC, merged