Add DracFun to addon list
Slimefun/Wiki pull request #254
Opened 2023-10-03 13:16 UTC by PhoenixCodingStuff

~~Also when will my application be reviewed.~~

2023-10-03 15:11 UTC, svr333 commented
Your application for what?

While the requirements don't say it has to be open-source I think it is enforced? Though I'm not sure so @Sefiraat what do you think?

And personally I find that
> I will probably open source in the future because lot of code is not complete and under comments

this should not be a reason to not open-source, sometimes code is just quick and messy but if it works it works, who cares what it looks like. Though that is just my opinion

2023-10-03 15:14 UTC, Sefiraat commented
Open source is a requirement for being on the builds repo but it's not one for the wiki as far as I know, and In my opinion I have no issues with it being closed here. That being said I do, without reservation, recommend you make it open source for many reasons. - regardless of your thoughts on its completeness and code quality. You will not be judged on that, but you may well be judged on the closed source nature, but that's your choice I guess.

2023-10-04 14:38 UTC, TheBusyBiscuit requested changes

2023-10-04 14:38 UTC, TheBusyBiscuit commented on pages/Addons.md
> +DracFun | Phoenix | <details><summary>expand</summary>DracFun adds new powerful tools, machines, and items which are based upon the plugin's main resource - Draconium.</details> | [Readme](https://mo
Don't call it a readme, if it's not a readme file.
```suggestion
DracFun | Phoenix | <details><summary>expand</summary>DracFun adds new powerful tools, machines, and items which are based upon the plugin's main resource - Draconium.</details> | [Modrinth](https://modrinth.com/plugin/dracfun) | N/A | [Modrinth](https://modrinth.com/plugin/dracfun/versions)
```

2023-10-04 14:48 UTC, TheBusyBiscuit commented
> I will probably open source in the future because lot of code is not complete and under comments👍
> ~Also it is unoptimized asf. [...]
> The requirements did not say it needs to be open source so I will update GitHub link in the future with PR 

Yep, that's fine 👍🏻
The projects do not need to be open-source to be listed here but open-source is undisputedly superior ;)

2023-10-05 17:58 UTC, TheBusyBiscuit approved these changes

2023-10-07 00:17 UTC, Phoenix-Starlight approved these changes
Hopefully the pull bot doesn't force push this, no comments aside. Welcome to the addon list.

2023-10-07 00:18 UTC, merged