Update links to addons in the wiki
Slimefun/Wiki pull request #272
Opened 2024-02-25 18:28 UTC by Boomer-1

This PR will update the links to download the addons who have moved to blob.build that have not yet been updated.

2024-02-27 15:55 UTC, WalshyDev submitted a review, later dismissed

2024-02-28 18:05 UTC, ybw0014 requested changes

2024-02-28 18:05 UTC, ybw0014 commented on pages/Addons.md
> +MobCapturer | TheBusyBiscuit | <details><summary>expand</summary>This Addon adds a Mob Capturing Cannon which you can use to capture mobs as items. You can find more info on the project page, it is i
```suggestion
MobCapturer | TheBusyBiscuit | <details><summary>expand</summary>This Addon adds a Mob Capturing Cannon which you can use to capture mobs as items. You can find more info on the project page, it is inspired by the Safari-Nets from the mod MineFactory Reloaded.</details> | [GitHub](https://github.com/Slimefun-Addon-Community/MobCapturer) | [Builds](https://blob.build/project/MobCapturer)
```

2024-03-02 18:37 UTC, WalshyDev approved these changes

2024-03-04 11:50 UTC, Sfiguz7 approved these changes

2024-03-04 11:50 UTC, merged