Add new talismans to the wiki
Slimefun/Wiki pull request #74
Opened 2020-10-04 18:51 UTC by svr333

- Add Talisman of the Caveman
- Add Talisman of the Wise (PR not yet merged in Slimefun)
- Add Talisman of the Resurrected (PR not yet merged in Slimefun)

2020-10-04 18:56 UTC, LinoxGH requested changes

2020-10-04 18:56 UTC, LinoxGH commented on pages/Talismans.md
> +| Talisman of the Caveman | Has a 50% chance to give you haste when mining ores | No |
Since haste is an effect name it should be `Haste` just like other effects.

2020-10-05 15:07 UTC, LinoxGH requested changes

2020-10-05 15:07 UTC, LinoxGH commented on pages/Talismans.md
> +| Talisman of the Resurrected | Respawns you to a safe location if you fall in the void | Yes |
```suggestion
| Talisman of the Caveman | Has a 50% chance to give you Haste after mining an ore | No |
| Talisman of the Wise | Has a 20% chance to double your experience drop | No |
| Talisman of the Resurrected | Respawns you to a safe location if you fall into the void | Yes |
```
Sorry for the delay

2020-10-07 12:33 UTC, LinoxGH approved these changes

2021-02-05 19:56 UTC, svr333 commented
The original PR isn't getting merged so Ill close this with it

2021-02-05 19:56 UTC, closed without merging