Added /sf charge to the wiki
Slimefun/Wiki pull request #81
Opened 2020-11-11 21:43 UTC by NCBPFluffyBear

2020-11-11 22:08 UTC, TheBusyBiscuit requested changes
Could you please also add the permission to Permissions.md?

2020-11-11 22:08 UTC, TheBusyBiscuit commented on pages/Commands.md
> +| /sf charge | Charges the item in your hand. | slimefun.command.charge |
Should probably say that it **fully** charges the item.

2020-11-12 09:37 UTC, TheBusyBiscuit approved these changes

2020-11-17 14:39 UTC, svr333 approved these changes

2020-11-17 14:40 UTC, merged