Include disable researching to FAQ
Slimefun/Wiki pull request #95
Opened 2020-12-27 23:35 UTC by WalshyDev

This question gets asked a lot in Discord so let's stick it in the FAQ

2020-12-29 00:26 UTC, svr333 requested changes

2020-12-29 00:28 UTC, WalshyDev commented on pages/FAQ.md
> +## How to disable all researching?
How about just "How to disable all or specific researches?"
Not sure how to say that... specific researching?

2020-12-30 12:22 UTC, svr333 commented on pages/FAQ.md
> +## How to disable all researching?
yup thatll definitely do

2020-12-30 20:38 UTC, TheBusyBiscuit commented on pages/FAQ.md
> +## How to disable all researching?
"individual" instead of "specific" perhaps?
Otherwise I also like that heading more than the current one.

2020-12-31 14:07 UTC, svr333 approved these changes

2020-12-31 14:26 UTC, TheBusyBiscuit approved these changes

2020-12-31 14:26 UTC, merged