Created Electric Furnace wiki page
Slimefun/Wiki pull request #96
Opened 2020-12-30 18:22 UTC by bryansha

First time contributing to this wiki and I did my best to follow the same design as the other wiki page

Let me know if anything needs fixing thanks!!!

2020-12-30 20:41 UTC, TheBusyBiscuit requested changes
Looks good, some small mistakes were made though.

Also please use lower-case for file extensions, so `.png`, not `.PNG`

2020-12-30 20:41 UTC, TheBusyBiscuit commented on pages/Electric-Furnace.md
> +The Electric Furnace is crafted in the [Enhanced Crafting Table](https://github.com/TheBusyBiscuit/Slimefun4/wiki/Enhanced-Crafting-Table). The recipes vary with the machine levels and can be found i
Missing dot (`.`) at the end here.

2020-12-30 20:41 UTC, TheBusyBiscuit commented on pages/Electric-Furnace.md
> +
ehm, no need for this many new lines.

2020-12-30 20:41 UTC, TheBusyBiscuit commented on pages/Electric-Furnace.md
> +And the slots of an Electric Furnace III is shown below:
* are

2020-12-30 20:41 UTC, TheBusyBiscuit commented on pages/Electric-Furnace.md
> +Once the output slots are filled, the Electric Furnaces stops its operation until the output slots are cleared. Therefore, a [Cargo Management System](https://github.com/Slimefun/Slimefun4/wiki/Cargo
Agtain, missing dot at the end.

2020-12-30 21:32 UTC, bryansha commented
All Fixed. Not too familiar with pull request so don't know if the edits worked....

2020-12-30 23:36 UTC, Phoenix-Starlight commented
> 
> 
> All Fixed. Not too familiar with pull request so don't know if the edits worked....

Replies about github and how this works. PRs will automatically update to reflect changes in the repo that is being merged into here. So dont worry, your PR will auto-update in response to commits to your fork of the wiki.

2020-12-31 13:39 UTC, svr333 commented
#93 also adds this page :/

2020-12-31 19:47 UTC, bryansha commented
> #93 also adds this page :/

!!!! wow I didn't notice.... I assumed it wasn't done as the link that leads to electric furnace said it wasn't written yet.

Looks like all those links have to be updated soon

2020-12-31 19:56 UTC, closed without merging

2021-01-03 22:24 UTC, svr333 commented
@bryansha Yeah sorry about this, we really appreciate you making this page
but #93 is still in progress and still requires to be merged, so it isnt fully merged yet and therefore the links arent updated yet